{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-scaler
  labels:
    {{- include "helm.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keda-scaler
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-scaler
  labels:
    {{- include "helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-scaler
subjects:
- kind: ServiceAccount
  name: keda-scaler
  namespace: {{ .Release.Namespace }}
{{- end }}
