{{- if .Values.enabled }}
{{- range .Values.deployments }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: scaledobject
    helm.sh/chart: {{ include "helm.chart" . }}
spec:
  scaleTargetRef:
    name: {{ .name }}
  minReplicaCount: {{ $.Values.scaleDownReplicas }}
  cooldownPeriod: 300
  triggers:
  - type: cron
    metadata:
      timezone: Etc/UTC
      start: {{ $.Values.scaleUpCronUtc }}
      end: {{ $.Values.scaleDownCronUtc }}
      desiredReplicas: "{{ .replicaCount }}"
{{- end }}
{{- end }}