{{- if .Values.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keda-scaler
spec:
  provider: aws
  secretObjects:
  - data:
    - key: SLACK_WEBHOOK_URL
      objectName: SLACK_WEBHOOK_URL
    secretName: keda-slack-notifications
    type: Opaque
  parameters:
    region: {{ .Values.global.aws.region }}
    objects: |
        - objectName: "pp/slack/keda-slack-notifications"
          objectType: secretsmanager
          jmesPath:
          - path: SLACK_WEBHOOK_URL
            objectAlias: SLACK_WEBHOOK_URL
{{- end }}